In [2]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

In [3]:
dataset_path = "assets/animals"

idg = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.1,

    rotation_range=10,   #degree
    zoom_range=0.1,   #percent
    horizontal_flip=True
)

dataset_train = idg.flow_from_directory(
    dataset_path,
    shuffle=True,
    # save_to_dir="/content/drive/MyDrive/dataset/animal_test",
    subset="training",
    target_size= (224,224)
)

dataset_validation = idg.flow_from_directory(
    dataset_path,
    shuffle=True,
    subset="validation",
    target_size= (224,224)
)

Found 1194 images belonging to 5 classes.
Found 130 images belonging to 5 classes.


In [6]:
a,b=dataset_validation[0]

ValueError: not enough values to unpack (expected 3, got 2)

In [9]:
print(a[0])

[[[0.93194574 0.6234088  0.36168933]
  [0.9059247  0.59846944 0.31378886]
  [0.87793905 0.5740996  0.2738534 ]
  ...
  [0.9058824  0.72156864 0.6509804 ]
  [0.90584344 0.7215297  0.6509415 ]
  [0.9052695  0.7209557  0.6503675 ]]

 [[0.9330698  0.6250949  0.36730966]
  [0.911545   0.60352767 0.32221934]
  [0.88131124 0.5769097  0.27834964]
  ...
  [0.90287703 0.71856326 0.647975  ]
  [0.902303   0.71798927 0.64740103]
  [0.90196085 0.7176471  0.64705884]]

 [[0.93419385 0.626781   0.37292993]
  [0.9171653  0.608586   0.33064982]
  [0.88468343 0.5797199  0.2828459 ]
  ...
  [0.90196085 0.7176471  0.64705884]
  [0.90196085 0.7176471  0.64705884]
  [0.90196085 0.7176471  0.64705884]]

 ...

 [[0.7182445  0.3260876  0.20059736]
  [0.72054034 0.3283835  0.20289329]
  [0.7228363  0.3306794  0.2051892 ]
  ...
  [0.8765938  0.90012324 0.99424094]
  [0.87843144 0.90196085 0.9960785 ]
  [0.88321346 0.90196085 0.99846953]]

 [[0.7324062  0.3402493  0.2147591 ]
  [0.732649   0.34049213 0.21500193]


In [16]:
model = models.Sequential([
    layers.Conv2D(32, (3, 3), strides=(2, 2), activation="relu", padding="same", input_shape=(224, 224, 3)),
    layers.MaxPooling2D(),
    layers.Conv2D(64, (3, 3), strides=(2, 2), activation="relu", padding="same"),
    layers.MaxPooling2D(),
    # layers.Conv2D(128, (3, 3), strides=(1, 1), activation="relu"),
    # layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(256, activation="relu"),
    layers.Dense(512, activation="relu"),
    layers.Dense(5, activation="softmax"),
])

model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
              loss = tf.keras.losses.categorical_crossentropy,
              metrics = ['accuracy'])

history = model.fit(dataset_train, validation_data=dataset_validation, epochs=20)

model.save('weights/animals.h5')

Epoch 1/20
38/38 [==============================] - 45s 1s/step - loss: 1.5669 - accuracy: 0.2931 - val_loss: 1.4553 - val_accuracy: 0.3462
Epoch 2/20
38/38 [==============================] - 28s 740ms/step - loss: 1.3633 - accuracy: 0.3894 - val_loss: 1.2521 - val_accuracy: 0.4846
Epoch 3/20
38/38 [==============================] - 27s 702ms/step - loss: 1.1530 - accuracy: 0.4992 - val_loss: 1.2431 - val_accuracy: 0.4538
Epoch 4/20
38/38 [==============================] - 27s 711ms/step - loss: 1.0627 - accuracy: 0.5461 - val_loss: 1.1291 - val_accuracy: 0.5308
Epoch 5/20
38/38 [==============================] - 27s 709ms/step - loss: 0.9985 - accuracy: 0.5980 - val_loss: 1.0731 - val_accuracy: 0.5308
Epoch 6/20
38/38 [==============================] - 26s 698ms/step - loss: 0.8733 - accuracy: 0.6491 - val_loss: 1.0672 - val_accuracy: 0.5769
Epoch 7/20
38/38 [==============================] - 27s 724ms/step - loss: 0.7755 - accuracy: 0.6918 - val_loss: 1.2105 - val_accuracy: 0.5077
Ep

In [28]:
import os
import numpy as np
import cv2
import tensorflow as tf

data_folder = 'animals'
images = []
files = []
feature = dict()
featuress = []

for f in os.listdir(data_folder) :
    files.append(f)

files.sort()
print(files)

model = tf.keras.models.load_model('weights/animals.h5')
image = cv2.imread('test/cat2.jpg')
image = cv2.resize(image, (224,224))
image = np.array(image)/255
# print(image.shape)
image = np.expand_dims(image, axis=0) 
# print(image.shape)
result = model.predict(image)
# print(result)

out = np.argmax(result)
# print(out)
files[out]

['cat', 'dog', 'elephant', 'giraffe', 'panda']
1/1 [==============================] - 0s 84ms/step


'cat'

In [1]:
a,b= dataset_validation

NameError: name 'dataset_validation' is not defined